baseURL = "/"
languageCode = "en-us"
title = "Ani Writes"
theme = "hugo-swift-theme"
author = "Ani"

copyright = "Kumar Anirudha"
canonifyurls = true
paginate = 6
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

disqusShortname = "blog-anirudha"

[params]
  subtitle = "Solitary pursuits of a curious geek"
  description = "Tech Scribblings and Tinkerings"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "kranirudha" # twitter handle e.g @weru
  # logo = "logo.png"
  author = "Ani" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
  gitProvider = "github"  # Either "github" or "gitlab"
  username = "anistark"  # GitHub/GitLab user name
  repository = "blog"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>
